Initial Code Review
pacificclimate/p2a-rule-engine pull request #1
Opened 2019-01-24 00:46 UTC by nikola-rados

The code in this branch is meant to run with test data and thus some of its data access/acquisition does not represent what the final product will look like.  The goal is to have the climate explorer backend provide the rule engine with data where it needs it.

For now though I'm hoping for a general code review to ensure the project has a good baseline before merging into master and moving forward.  Some information on the basic flow of the program can be found in the ```README.md```

2019-01-24 22:10 UTC, rod-glover requested changes
Good job. A few suggestions on programming style, which directly affect understandability.

2019-01-24 22:10 UTC, rod-glover commented on scripts/evaluator.py
> +def sub_str_value(data, pt_d, variable_getter):
The purpose and name of this function is not immediately obvious.

- Add a docstring defining what it does. E.g., "Given the name of a terminal symbol in an rule expression, return either the value of that symbol if it is a variable or the parse tree for that symbol if it is a rule."
- Rename it with a more descriptive name. E.g., `get_symbol_value`.

The names of its parameters are also not all very clear.
- Rename `data` -> `symbol_name`
- Rename `pt_d` -> `parse_trees` or `rules`

Good naming really affects understandability, which is key to maintainability. In general:

- Avoid abbreviations (e.g., don't use `pt_d`)
- For variables, name in the form of a noun phrase (e.g., `parse_trees`)
- Don't include the type of the variable in its name (e.g., don't call it `parse_tree_dict`, call it `parse_trees`)
- For functions, name in the form `<verb>_<noun phrase>`. E.g., `get_symbol_value`

2019-01-24 22:10 UTC, rod-glover commented on scripts/evaluator.py
> +    elif op == '&&':
The following operators shouldn't be treated as special cases. Add them to your `ops` object.

2019-01-24 22:10 UTC, rod-glover commented on scripts/evaluator.py
> +    ops = {'+' : operator.add,
This is probably best declared outside of the function, and possibly then given a slightly longer and more explicit name.

2019-01-24 22:10 UTC, rod-glover commented on scripts/evaluator.py
> +def evaluate_parse_tree(pt, pt_d, variable_getter):
Docstring and names again. 

Always write your docstring early. It will guide what you name things, amongst other benefits. In this case, an accurate description is that this function evaluates the value of a symbol, which may be be a constant or a rule defined by a parse tree. That description reveals that `evaluate_parse_tree` is really `evaluate_symbol`, and `pt` is really the name of the symbol (and hence should have a name like `symbol_name`), etc.

2019-01-24 22:10 UTC, rod-glover commented on scripts/evaluator.py
> +                            evaluate_parse_tree(pt[3], pt_d, variable_getter))
I realized after discussing this with you that there is a nice way to avoid having to pass the parse trees and the variable getter down the function. It's called a helper function, and it takes advantage of scoping:

Inside this function (`evaluate_parse_tree` or whatever it ends up being named, call it `e` for now), define a helper function `f(x)` (pick better names, but don't shadow outer names). `f` does most of the work, and it absorbs basically all the code of `e`.

Due to how scoping works, `f` has all the parameters of `e` available to it (globally), and so does not need them passed in explicitly. 

So you get

```python
def e(a, b, c):
    def f(x):
        // body using b, c
    
    return f(a)
```

2019-01-24 22:10 UTC, rod-glover commented on scripts/data_acquisition.py
> +    with open(filename) as json_data:
Oof. Don't (re)open the file for every variable. Open it only once!

2019-01-24 22:10 UTC, rod-glover commented on scripts/resolver.py
> +    TERNARY = r'\?'
"Ternary" is a general term that means "three operands". The `?` operator is a ternary operator, and it is called the conditional operator. Should call it that.

2019-01-24 22:10 UTC, rod-glover commented on scripts/resolver.py
> +    # still unsure about how 'correct' this section is
Me too. Consult a standard language (Python!) and use its precedence rules for the equivalent operators.

2019-01-24 22:10 UTC, rod-glover commented on scripts/resolver.py
> +    def expr(self, p):
Kewl!

2019-01-24 22:10 UTC, rod-glover commented on scripts/resolver.py
> +       )
Can these be included in the declaration for +, -, etc.?

2019-01-24 22:10 UTC, rod-glover commented on tests/test_evaluator.py
> +    (('?', True, 1, 0), None, None, 1),
Please add a test case for condition == `False`.

2019-01-24 22:10 UTC, rod-glover commented on tests/test_evaluator.py
> +    (('&&', True, False), None, None, False),
Please add at least one other test case for `&&`.

2019-01-24 22:10 UTC, rod-glover commented on tests/test_evaluator.py
> +    (('||', True, False), None, None, True),
Please add at least one other test case for `||`.

2019-01-24 22:10 UTC, rod-glover commented on tests/test_evaluator.py
> +     partial(get_val_from_dict, {'temp_djf_iamean_s0p_hist': -10}), -10)
Nice.

2019-01-24 22:10 UTC, rod-glover commented on tests/test_resolver.py
> +    assert expected_tree, expected_vars == build_parse_tree(data)
:100:

2019-01-24 22:10 UTC, rod-glover commented on tests/test_resolver.py
> +    assert test_vars == set()
Overall, good tests. Nice job.

2019-01-24 23:10 UTC, nikola-rados commented on scripts/evaluator.py
> +    ops = {'+' : operator.add,
When you say outside, do you mean it should be passed in as a parameter or just exist as a global?

2019-01-24 23:23 UTC, nikola-rados commented on scripts/evaluator.py
> +                            evaluate_parse_tree(pt[3], pt_d, variable_getter))
Great find!

2019-01-25 17:30 UTC, rod-glover commented on scripts/evaluator.py
> +    ops = {'+' : operator.add,
Just exist as a global. It would be amusing to pass it as a parameter, but that's not necessary unless you are really contemplating changing the meaning of `+` and `-` !

2019-01-25 18:58 UTC, nikola-rados commented
Thank you for your feedback @rod-glover I appreciate it!  I have implemented the changes you have recommended and will be merging into master.

2019-01-25 19:00 UTC, merged